apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-core-project.yaml
  - external-secrets-app.yaml
  - operator-orchestration-service-app.yaml
  - platform-vault-reader-serviceaccount.yaml
  - platform-vault-secretstore.yaml
  - platform-engineering-repo-externalsecret.yaml
  - vault-app.yaml
