apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-orchestration-service
  namespace: argocd
spec:
  project: platform-core
  source:
    repoURL: https://github.com/mfshaf7/platform-engineering.git
    targetRevision: main
    path: environments/shared/operator-orchestration-service
  destination:
    server: https://kubernetes.default.svc
    namespace: operator-orchestration-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
