apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-core
  namespace: argocd
spec:
  description: Platform workloads and supporting services
  sourceRepos:
    - https://github.com/mfshaf7/platform-engineering.git
    - oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    - https://charts.external-secrets.io
    - https://helm.releases.hashicorp.com
    - https://charts.openproject.org
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: openclaw
      server: https://kubernetes.default.svc
    - namespace: openclaw-stage
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
    - namespace: observability-stage
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: platform-postgresql
      server: https://kubernetes.default.svc
    - namespace: openproject
      server: https://kubernetes.default.svc
    - namespace: operator-orchestration-service
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
