apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-dashboards-app.yaml
  - openclaw-prod-lifecycle-configmap.yaml
  - platform-postgresql-secrets-app.yaml
  - platform-postgresql-app.yaml
  - openproject-secrets-app.yaml
  - openproject-app.yaml
  - observability-app.yaml
