apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openclaw-platform-project.yaml
  - openclaw-gateway-app.yaml
  - platform-version-app.yaml
  - observability-app.yaml
  - external-secrets-app.yaml
