apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgresql-secrets
  namespace: argocd
spec:
  project: platform-core
  source:
    repoURL: https://github.com/mfshaf7/platform-engineering.git
    targetRevision: main
    path: environments/prod/platform-postgresql-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
