apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-version
  namespace: argocd
spec:
  project: platform-core
  source:
    repoURL: https://github.com/mfshaf7/platform-engineering.git
    targetRevision: main
    path: charts/platform-version
    helm:
      valueFiles:
        - ../../environments/prod/values/platform-version.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
