apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operator-orchestration-service
resources:
  - serviceaccount.yaml
  - secretstore.yaml
  - operator-orchestration-service-externalsecret.yaml
  - deployment.yaml
  - service.yaml
