apiVersion: v1
kind: Service
metadata:
  name: operator-orchestration-service
spec:
  type: ClusterIP
  selector:
    app: operator-orchestration-service
  ports:
    - name: http
      port: 8080
      targetPort: http
