apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - grafana-admin-serviceaccount.yaml
  - grafana-admin-secretstore.yaml
  - grafana-admin-externalsecret.yaml
  - operator-ui-auth-externalsecret.yaml
  - operator-ui-auth-proxy.yaml
  - platform-overview-dashboard.yaml
