apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-operator-ui-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: platform-vault
  target:
    name: platform-operator-ui-auth
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: platform/observability/prod/operator-ui-auth
        property: htpasswd
