apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-gateway-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-core
  source:
    repoURL: https://github.com/mfshaf7/platform-engineering.git
    targetRevision: main
    path: charts/openclaw-gateway
    helm:
      valueFiles:
        - ../../environments/stage/values/openclaw-gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
