apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-version-stage
  namespace: argocd
spec:
  project: openclaw-platform
  source:
    repoURL: https://github.com/mfshaf7/platform-engineering.git
    targetRevision: main
    path: charts/openclaw-platform-version
    helm:
      valueFiles:
        - ../../environments/stage/values/platform-version.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
