apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openproject
resources:
  - serviceaccount.yaml
  - secretstore.yaml
  - openproject-admin-external-secret.yaml
  - openproject-postgresql-credentials-external-secret.yaml
