#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
TARGET_LOGIN="${TARGET_LOGIN:-${OPENPROJECT_AUTOMATION_LOGIN:-operator-orchestration-service}}"
TARGET_FIRSTNAME="${TARGET_FIRSTNAME:-${OPENPROJECT_AUTOMATION_FIRSTNAME:-Operator}}"
TARGET_LASTNAME="${TARGET_LASTNAME:-${OPENPROJECT_AUTOMATION_LASTNAME:-Orchestration Service}}"
TARGET_MAIL="${TARGET_MAIL:-${OPENPROJECT_AUTOMATION_MAIL:-operator-orchestration-service@local.invalid}}"
TARGET_PROJECT_IDENTIFIER="${TARGET_PROJECT_IDENTIFIER:-${OPENPROJECT_AUTOMATION_PROJECT_IDENTIFIER:-workspace-proposals}}"
TARGET_PROJECT_IDENTIFIERS_JSON="${TARGET_PROJECT_IDENTIFIERS_JSON:-${OPENPROJECT_AUTOMATION_PROJECT_IDENTIFIERS_JSON:-}}"
TARGET_TOKEN_NAME="${TARGET_TOKEN_NAME:-${OPENPROJECT_AUTOMATION_TOKEN_NAME:-openproject-workspace-proposals-v1}}"
TARGET_ROLE_NAMES_JSON="${TARGET_ROLE_NAMES_JSON:-${OPENPROJECT_AUTOMATION_ROLE_NAMES_JSON:-[\"Reader\",\"Work package creator\",\"Work package editor\",\"Work package structure editor\"]}}"
ROTATE_API_TOKEN="${ROTATE_API_TOKEN:-${OPENPROJECT_ROTATE_API_TOKEN:-false}}"
ISSUE_API_TOKEN="${ISSUE_API_TOKEN:-true}"
VAULT_SECRET_PATH="${VAULT_SECRET_PATH:-kv/components/operator-orchestration-service/prod/openproject}"

export TARGET_LOGIN
export TARGET_FIRSTNAME
export TARGET_LASTNAME
export TARGET_MAIL
export TARGET_PROJECT_IDENTIFIER
export TARGET_PROJECT_IDENTIFIERS_JSON
export TARGET_TOKEN_NAME
export TARGET_ROLE_NAMES_JSON
export ROTATE_API_TOKEN
export ISSUE_API_TOKEN
export VAULT_SECRET_PATH

exec "${REPO_ROOT}/products/openproject/scripts/openproject_provision_identity.sh"
